import type { SketchDocument } from "../../cad/model/types";
import { emitCutEnd, emitCutStart, emitMoveTo } from "./emitters";
import { fmt } from "./format";
import { shapeToToolpaths } from "./shapeToToolpath";

export async function generateSketchGCode(doc: SketchDocument): Promise<string> {
  const lines: string[] = [
    "; Generated by GCode Studio / CAD module",
    "G21",
    "G90",
    `G0 Z${fmt(doc.safeZ)}`,
  ];

  for (const shape of doc.shapes) {
    const toolpaths = await shapeToToolpaths(shape, doc);
    for (const toolpath of toolpaths) {
      if (toolpath.points.length < 2) continue;
      lines.push(`; ${toolpath.name}`);
      lines.push(...emitMoveTo(toolpath.points[0].x, toolpath.points[0].y, doc.feedRapid));
      lines.push(...emitCutStart(doc, toolpath.cutZ));
      for (let i = 1; i < toolpath.points.length; i += 1) {
        lines.push(`G1 X${fmt(toolpath.points[i].x)} Y${fmt(toolpath.points[i].y)} F${fmt(doc.feedCut)}`);
      }
      if (toolpath.closed) {
        lines.push(`G1 X${fmt(toolpath.points[0].x)} Y${fmt(toolpath.points[0].y)} F${fmt(doc.feedCut)}`);
      }
      lines.push(...emitCutEnd(doc));
    }
  }

  lines.push(`G0 Z${fmt(doc.safeZ)}`);
  lines.push("G0 X0 Y0");
  return lines.join("\n") + "\n";
}

