// src/gcode/emitters.ts

import type { MachineSettings } from "../types";
import { fmt } from "./format";

function spindleMCode(machine: MachineSettings): "M3" | "M4" {
  return machine.spindle?.direction === "ccw" ? "M4" : "M3";
}

export function emitProgramPreamble(machine: MachineSettings): string[] {
  const lines: string[] = [
    "; Generated by @gcode-studio/cam",
    machine.units === "inch" ? "G20" : "G21",
    "G90 G17",
    machine.workOffset ?? "G54",
    `T${Math.max(1, Math.round(machine.toolNumber ?? 1))} M6`,
    `G0 Z${fmt(machine.startZ)}`,
  ];

  if (machine.coolant) lines.push("M8");
  return lines;
}

export function emitProgramPostamble(machine: MachineSettings): string[] {
  const lines: string[] = [];
  if (machine.spindle?.enabled) lines.push("M5");
  if (machine.coolant) lines.push("M9");
  lines.push(`G0 Z${fmt(machine.safeZ)}`);
  if (machine.returnHome) lines.push("G0 X0 Y0");
  lines.push("M30");
  return lines;
}

export function emitMoveTo(x: number, y: number): string[] {
  return [`G0 X${fmt(x)} Y${fmt(y)}`];
}

export function emitToolStart(machine: MachineSettings): string[] {
  if (!machine.spindle?.enabled) return [];
  const lines: string[] = [];
  lines.push(`${spindleMCode(machine)} S${Math.max(0, Math.round(machine.spindle.speed))}`);
  if ((machine.spindle.dwellMs ?? 0) > 0) lines.push(`G4 P${fmt(machine.spindle.dwellMs ?? 0)}`);
  return lines;
}

export function emitPlungeTo(machine: MachineSettings, cutZ: number): string[] {
  return [`G1 Z${fmt(cutZ)} F${fmt(machine.feedPlunge)}`];
}

export function emitToolEnd(machine: MachineSettings): string[] {
  return [`G0 Z${fmt(machine.safeZ)} F${fmt(machine.feedRapid)}`];
}

export function emitCutStart(machine: MachineSettings, cutZ: number): string[] {
  return [...emitToolStart(machine), ...emitPlungeTo(machine, cutZ)];
}

export function emitCutEnd(machine: MachineSettings): string[] {
  return emitToolEnd(machine);
}
